### ISSUE TITLE
Neveikia ant GeexBox (XBMC Gotham) distribucijos Cubox v1 įrenginyje

### ISSUE THREAD

**Issue by misterixas** [Vytax/plugin.video.lnk.lt#1]
Labas, Vytax

Jau kelis metus turiu Cubox įrenginuką iš SolidRun. Pasidariau jį kaip HTPC, t.y. jame sukasi GeeXBox (XBMC 13.2 Gotham). Su savo "pričiūdais", bet bendrai paėmus esu visai patenkintas. Gaila, tik kad tai pirmas-bandyminis produktas iš SolidRun, kaip sakoma "pirmas blynas" (o aš ir taip linux'uose žalias) todėl tikriausiai net porai metų nepraėjus, gamintojas suskubo pašalinti jį tiek iš prekybos, tiek iš support'o, tiek ir dokumentacijos. Bet aš ne apie tai.  Daugiausia naudoju angliškus ir rusiškus video repositorius. Neseniai pasidomėjau, o kiap su lietuviškais, bet apart tavo, nieko neradau. Susimečiau viskas veikia kuo puikiausiai, išskyrus LNK. Po meniu vaikšto normaliai, rodo visus laidų, serialų ir t.t. pavadinimus, bet kai bandau kurį nors paleisti, nieko nevyksta, o po keliolikos sekundžių parodo lentelę "Playback failed check log for details". Kame galėtų būti bėda?

Misterixas

**Comment by asleiniu** [comment]
Sveiki,

As turiu tik Cubox-i4  antra varianta    ir dabar  su openelec 6.0 (Kodi
15.2).  Berods versijos tokios. Su lietuviskais pluginsiais viskas veikia.
LNK GO irgi . Dakara vaikas per ji ziuri. tik   laidu pasirinkimui  tekstas
nuo pradzio atitrauktas gal per 10 -15 tarpu, bet tai ne  didele problema.

LNK-GO pries kelis metus buvo kitas pluginsas kuris bent man nustojo veikti
(ar net ir neveike - dabar nepamenu)...

Pries kaledas giminaiciams tvarkiau minix x8h-plus  irgi kodi 15.2 . taip
pat lietuviski vytax pluginsai veikia be problemu.
Tai gal Kodi versija kitokia?

Didelis aciu Vytax uz pluginsus...

Pagarbiai,
Arturas

2016 m. sausio 12 d. 08:52, misterixas notifications@github.com rašė:

**Comment by Vytax** [comment]
Sveiki,
LNK smarkiai apribojo prieinamumą prie video įrašų. Todėl įskiepis LNK kurį laiką nerodys.
Vis dar ieškau būdų kaip šias problemas apeiti.

**Comment by misterixas** [comment]
Dėkui Artūrui ir Vytaxui už atsakymus. Jau galvojau į internetą įkelti debug log failą, bet netikėtai šį vakarą viskas iš LNKGO plugino rodo. Rodo ir iš kitų lietuviškų. Tikėkimės taip bus ir toliau.

Dar kartą ačiū Vytax už pluginus ir nuo manęs. Padarei darbą, kurio Lietuvoje dar niekas nebuvo padaręs. Varyk taip ir toliau!

**Comment by Vytax** [comment]
Pataisiau įskiepį. Pakeičiau streamURL iš HLS į RTMP. Dabar turėtų šiek tiek sparčiau atverti video įrašus. 
Nors panašu, kad LNK serveriai susiduria su per dideliu apkrovimu. Todėl piko metu gali būti problemų. Bet tai jau ne šio Kodi įskiepio problema.
